add Clear method to DriveFS interface, delete unused DriveOptions
proximax-storage/go-xpx-dfms-api pull request #41
Opened 2020-11-17 15:29 UTC by jenyasd209

2020-11-17 15:45 UTC, xgreenx approved these changes

2020-11-17 15:45 UTC, xgreenx commented on drive_fs.go
> +	// NOTE: Removes only reference to the file.
Removes references to the file. If reference is last, then remove file.

2020-11-18 10:33 UTC, Wondertan requested changes

2020-11-18 10:33 UTC, Wondertan commented on drive_fs.go
> +	// NOTE: Removes only reference to the file. If reference is last, then remove file.
```suggestion
	// NOTE: Removes only reference to the file. If the reference is las and the file is cached, then it removes the file from the cache.
```

2020-11-19 10:53 UTC, Wondertan approved these changes

2020-11-19 11:04 UTC, merged